#ESTE PROGRAMA VISA IMPLEMENTAR TODAS AS FUNÇÕES DA CLASSE LINKEDLIST, CHAMANDO CADA FUNÇÃO/MÉTODO AFIM DE OBTER OS RESULTADOS E MANIPULAR ALGUM OUTPUT

from views import view

if __name__ == "__main__":
    view.main()